import { InMemoryDbService, RequestInfo } from 'angular-in-memory-web-api';

export class MockedTodoService implements InMemoryDbService {

    createDb() {
        return {
            todos: [
                { id: 1, title: 'First todo', done: false, description: this.getDesc(1), lastChange: Date.parse('2019-01-01'), },
                { id: 2, title: 'Second todo', done: true, description: this.getDesc(2), lastChange: Date.parse('2019-02-01'), },
                { id: 3, title: 'Thrid todo', done: false, description: this.getDesc(3), lastChange: Date.parse('2019-03-01'), },
                { id: 4, title: 'Fourth todo', done: true, description: this.getDesc(4), lastChange: Date.parse('2019-04-01'), },
                { id: 5, title: 'Fifth todo', done: true, description: this.getDesc(5), lastChange: Date.parse('2019-05-01'), },
                { id: 6, title: 'Sixth todo', done: true, description: this.getDesc(6), lastChange: Date.parse('2019-06-01'), },
                { id: 7, title: 'Seventh todo', done: false, description: this.getDesc(7), lastChange: Date.parse('2019-07-01'), },
                { id: 8, title: 'Eighth todo', done: true, description: this.getDesc(8), lastChange: Date.parse('2019-08-01'), },
            ]
        };
    }

    private getDesc(todoId: number) {
        return 'This is a pretty long description for TODO' + todoId + ' generated by a method because ' +
            'it is way easier to write a method than to copy paste the description everywhere !';
    }
}
